"""
Render the Open Graph share card and the site icon.

Kept as a script rather than a one-off so the card can be regenerated when the
pitch changes, and so the thing that produced the bytes in the worker bundle is
visible in the repo rather than being a mystery blob.

    python scripts/make-og-image.py

Writes src/royale/assets/og.png (1200x630) and icon.png (512x512), then
src/royale/assets.ts, which embeds both as base64 for the Worker to serve.
Workers have no filesystem, so a static asset either lives in the bundle or
lives somewhere else that costs a request; for two small flat-colour PNGs the
bundle is the cheaper answer.
"""

import base64
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "src", "royale", "assets")
os.makedirs(ASSETS, exist_ok=True)

# The site's palette, so the card looks like the page it links to.
BG = (11, 13, 16)
PANEL = (20, 24, 29)
LINE = (35, 42, 50)
INK = (216, 222, 230)
DIM = (124, 135, 148)
ACCENT = (155, 227, 109)
PLAYER = (92, 200, 255)
MOB = (192, 122, 74)
LOOT = (224, 179, 65)

MONO = "C:/Windows/Fonts/consola.ttf"
MONO_BOLD = "C:/Windows/Fonts/consolab.ttf"


def font(path, size):
    try:
        return ImageFont.truetype(path, size)
    except OSError:
        return ImageFont.load_default()


def draw_arena(d, x0, y0, cell, gap, cols, rows, occupied):
    """A miniature of the spectator board — the thing being advertised."""
    for gy in range(rows):
        for gx in range(cols):
            x = x0 + gx * (cell + gap)
            y = y0 + gy * (cell + gap)
            d.rounded_rectangle([x, y, x + cell, y + cell], radius=3, fill=(15, 19, 23))
            what = occupied.get((gx, gy))
            if not what:
                continue
            pad = cell * 0.18
            box = [x + pad, y + pad, x + cell - pad, y + cell - pad]
            if what == "player":
                d.ellipse(box, fill=PLAYER)
            elif what == "mob":
                d.rounded_rectangle(box, radius=4, fill=MOB)
            elif what == "loot":
                m = cell * 0.32
                d.regular_polygon((x + cell / 2, y + cell / 2, cell / 2 - m + 6), 4, 45, fill=LOOT)
            elif what == "wall":
                d.rounded_rectangle([x, y, x + cell, y + cell], radius=3, fill=(39, 46, 54))


def make_og():
    W, H = 1200, 630
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)

    tag = font(MONO_BOLD, 22)
    title = font(MONO_BOLD, 60)
    body = font(MONO, 26)
    small = font(MONO, 23)

    x = 72
    d.text((x, 92), "AGENT WARS", font=tag, fill=ACCENT)

    # The headline is the pitch, not the product name. Somebody scrolling a
    # feed decides in about a second, and "my agent can beat up your agent"
    # needs no explaining to anybody who has ever had an argument aged nine.
    d.text((x, 142), "MY AGENT CAN", font=title, fill=INK)
    d.text((x, 208), "BEAT UP YOUR", font=title, fill=INK)
    d.text((x, 274), "AGENT.", font=title, fill=PLAYER)

    for i, line in enumerate(
        [
            "Autonomous agents fight, loot and",
            "survive in a live arena. No player",
            "interface — every combatant is",
            "somebody's agent, playing over MCP.",
        ]
    ):
        d.text((x, 372 + i * 34), line, font=body, fill=DIM)

    d.line([(x, 524), (x + 560, 524)], fill=LINE, width=2)
    d.text((x, 548), "mcpagentwars.com", font=small, fill=LOOT)

    # The board, right-hand side: a game in progress rather than a logo.
    occupied = {
        (1, 0): "wall", (4, 1): "mob", (2, 2): "player", (5, 3): "wall",
        (0, 3): "loot", (3, 4): "mob", (6, 2): "loot", (4, 5): "player",
        (2, 6): "wall", (6, 6): "mob", (1, 5): "loot", (5, 0): "mob",
    }
    draw_arena(d, 760, 148, cell=46, gap=6, cols=8, rows=8, occupied=occupied)

    path = os.path.join(ASSETS, "og.png")
    img.save(path, "PNG", optimize=True)
    return path


def make_icon():
    S = 512
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([0, 0, S, S], radius=96, fill=PANEL)
    occupied = {(0, 0): "player", (2, 1): "mob", (1, 2): "loot", (2, 2): "wall"}
    draw_arena(d, 96, 96, cell=96, gap=14, cols=3, rows=3, occupied=occupied)
    path = os.path.join(ASSETS, "icon.png")
    img.save(path, "PNG", optimize=True)
    return path


def embed(paths):
    lines = [
        "/**",
        " * Static images, base64 in the bundle.",
        " *",
        " * Generated by scripts/make-og-image.py — edit that and re-run rather",
        " * than touching this file. Workers have no filesystem, so a static asset",
        " * either ships in the bundle or costs a request somewhere else; for two",
        " * small flat-colour PNGs the bundle is the cheaper answer.",
        " */",
    ]
    for name, path in paths.items():
        with open(path, "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode("ascii")
        size = os.path.getsize(path)
        lines.append(f"\n/** {os.path.basename(path)} — {size:,} bytes */")
        lines.append(f'export const {name} = "{b64}";')
    lines.append("")
    lines.append("/** Base64 to bytes, for serving from a Worker. */")
    lines.append("export function pngBytes(b64: string): Uint8Array {")
    lines.append("  const bin = atob(b64);")
    lines.append("  const out = new Uint8Array(bin.length);")
    lines.append("  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);")
    lines.append("  return out;")
    lines.append("}")
    with open(os.path.join(ROOT, "src", "royale", "assets.ts"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    og = make_og()
    icon = make_icon()
    embed({"OG_PNG_B64": og, "ICON_PNG_B64": icon})
    print(f"og.png   {os.path.getsize(og):,} bytes")
    print(f"icon.png {os.path.getsize(icon):,} bytes")
    print("wrote src/royale/assets.ts")
